P8105_mtp_bz2561
================
Bohan Zhu
2025-10-18

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
library(patchwork)
```

# Import and Tidy Data

``` r
exostosis_df = 
  read_excel("data/p8105_mtp_data.xlsx", skip = 8, na = c("NA", ".", "")) |> 
  janitor::clean_names() 
  
exostosis_clean = 
  exostosis_df |> 
  mutate(
    sex= case_match(
      sex, 
      0 ~ "female",
      1 ~ "male"
    ),
    age_group = case_match(
      age_group,
      "2" ~ "18_30",
      "3" ~ "31_40",
      "4" ~ "41_50",
      "5" ~ "51_60",
      c("6", "7", "8") ~ "60+"
    ) |> 
      factor(levels = c("18_30", "31_40", "41_50", "51_60", "60+"),
           ordered = TRUE),
    eop_size_mm = if_else(is.na(eop_size_mm), 0, eop_size_mm),
    eop_size = case_match(
    eop_size,
    "0" ~ "0_5",
    "1" ~ "5_10",
    "2" ~ "10_15",
    "3" ~ "15_20",
    "4" ~ "20_25",
    "5" ~ "25+"
    ) |> 
      factor(levels = c("0_5", "5_10", "10_15", "15_20", "20_25","25+"),
           ordered = TRUE),
    eop_visibility_classification = case_match(
      eop_visibility_classification,
      0 ~ "eop size 0",
      1 ~ "0 < eop size  <=5",
      2 ~ "eop size >= 5"
    ) |> 
      factor(levels = c("eop size 0", "0 < eop size  <=5", "eop size >= 5"),
           ordered = TRUE),
    fhp_size_mm = if_else(is.na(fhp_size_mm), 0, fhp_size_mm),
    fhp_category = case_match(
      fhp_category,
      "0" ~ "0_10",
      "1" ~ "10_20",
      "2" ~ "20_30",
      "3" ~ "30_40",
      "4" ~ "40_50",
      "5" ~ "50_60",
      "6" ~ "60_70",
      "7" ~ "70+"
    ) |> 
      factor(levels = c("0_10", "10_20", "20_30", "30_40", "40_50",
                        "50_60","60_70","70+"),
           ordered = TRUE)
  )
```

The dataset was imported from an Excel file and cleaned by skipping
unused header rows, standardizing variable names, and converting missing
values into proper NAs. Each numeric code from the original report was
translated into meaningful labels for clarity. For example, sex was
recoded as male and female, and age groups were organized into ordered
categories such as 18–30, 31–40, 41–50, 51–60, and 60+.

Missing EOP size and FHP size measurements were replaced with zeros, and
both EOP and FHP size classifications were converted into readable,
ordered factor levels (e.g., 0–5 mm, 5–10 mm, 10–15 mm, etc.). The
variable eop_visibility_classification was also recoded to reflect
visibility categories (EOP size 0 mm, 0 \< EOP ≤ 5 mm, EOP ≥ 5 mm).

``` r
exostosis_clean |> 
  summarise(n())
```

    ## # A tibble: 1 × 1
    ##   `n()`
    ##   <int>
    ## 1  1221

``` r
exostosis_clean |> 
  group_by(sex) |> 
  summarise(participants = n()) |> 
  knitr::kable()
```

| sex    | participants |
|:-------|-------------:|
| female |          614 |
| male   |          607 |

``` r
exostosis_clean |> 
  group_by(age_group) |> 
  summarise(participants = n()) |> 
  knitr::kable()
```

| age_group | participants |
|:----------|-------------:|
| 18_30     |          303 |
| 31_40     |          204 |
| 41_50     |          207 |
| 51_60     |          200 |
| 60+       |          305 |
| NA        |            2 |

After cleaning, the resulting dataset contained 1221 observations and 9
variables. Among the variables, several are key to the analysis.

`EOP size` and `EOP visibility classification` are crucial because they
describe the prominence and visibility of the external enlarged
protuberance — the main anatomical feature studied. `FHP size` and
`FHP category` are also important, as they measure forward head posture,
which may be linked to EOP development. Finally, `sex` and `age group`
provide demographic context to explore biological or behavioral
differences across participants.

``` r
exostosis_clean |> 
  filter(is.na(age_group))
```

    ## # A tibble: 2 × 9
    ##   sex      age age_group eop_size_mm eop_size eop_visibility_classif…¹ eop_shape
    ##   <chr>  <dbl> <ord>           <dbl> <ord>    <ord>                        <dbl>
    ## 1 female    17 <NA>              6.4 5_10     eop size >= 5                    1
    ## 2 male      45 <NA>              0   0_5      eop size 0                      NA
    ## # ℹ abbreviated name: ¹​eop_visibility_classification
    ## # ℹ 2 more variables: fhp_size_mm <dbl>, fhp_category <ord>

``` r
exostosis_df |>
  filter(
    (eop_size_mm >= 0 & eop_size_mm < 5 & eop_size != 0) |
    (eop_size_mm >= 5 & eop_size_mm < 10 & eop_size != 1) |
    (eop_size_mm >= 10 & eop_size_mm < 15 & eop_size != 2) |
    (eop_size_mm >= 15 & eop_size_mm < 20 & eop_size != 3) |
    (eop_size_mm >= 20 & eop_size_mm < 25 & eop_size != 4) |
    (eop_size_mm >= 25 & eop_size != 5)
  ) |>
  select(eop_size_mm, eop_size)|> 
  knitr::kable()
```

| eop_size_mm | eop_size |
|------------:|:---------|
|       33.50 | 4        |
|       25.50 | 4        |
|       35.00 | 4        |
|       29.50 | 4        |
|        2.11 | 4        |
|       20.00 | 3        |
|       31.10 | 4        |
|       35.70 | 4        |
|       20.00 | 3        |
|       25.40 | 4        |
|       26.80 | 4        |
|       23.50 | 5        |
|       22.90 | 5        |
|       14.60 | 3        |
|       12.10 | 3        |
|        5.00 | 0        |
|       15.00 | 14.6     |

``` r
exostosis_clean |> 
  group_by(eop_shape) |> 
  summarise(participants = n()) |> 
  knitr::kable()
```

| eop_shape | participants |
|----------:|-------------:|
|         1 |          385 |
|         2 |           95 |
|         3 |          218 |
|         5 |            1 |
|        NA |          522 |

``` r
exostosis_clean |> 
  filter(is.na(fhp_size_mm))
```

    ## # A tibble: 0 × 9
    ## # ℹ 9 variables: sex <chr>, age <dbl>, age_group <ord>, eop_size_mm <dbl>,
    ## #   eop_size <ord>, eop_visibility_classification <ord>, eop_shape <dbl>,
    ## #   fhp_size_mm <dbl>, fhp_category <ord>

``` r
exostosis_clean |>
  filter(
    (fhp_size_mm >= 0  & fhp_size_mm < 10 & fhp_category != "0_10") |
    (fhp_size_mm >= 10 & fhp_size_mm < 20 & fhp_category != "10_20") |
    (fhp_size_mm >= 20 & fhp_size_mm < 30 & fhp_category != "20_30") |
    (fhp_size_mm >= 30 & fhp_size_mm < 40 & fhp_category != "30_40") |
    (fhp_size_mm >= 40 & fhp_size_mm < 50 & fhp_category != "40_50") |
    (fhp_size_mm >= 50 & fhp_size_mm < 60 & fhp_category != "50_60") |
    (fhp_size_mm >= 60 & fhp_category != "60_70" & fhp_category != "70+")
  ) |>
  select(fhp_size_mm, fhp_category) |> 
  knitr::kable()
```

| fhp_size_mm | fhp_category |
|------------:|:-------------|
|        54.1 | 40_50        |
|        63.6 | 40_50        |
|        54.9 | 40_50        |
|        80.2 | 40_50        |
|        54.9 | 40_50        |
|        52.7 | 40_50        |
|        52.1 | 40_50        |
|        54.7 | 40_50        |
|        89.3 | 40_50        |
|        52.7 | 40_50        |
|        51.4 | 40_50        |
|        54.2 | 40_50        |
|        53.6 | 40_50        |
|        51.2 | 40_50        |
|        57.9 | 40_50        |
|        21.1 | 10_20        |
|        33.8 | 10_20        |
|        56.6 | 40_50        |
|        22.9 | 10_20        |
|        31.8 | 20_30        |
|        60.1 | 40_50        |
|        30.1 | 10_20        |
|        31.5 | 20_30        |
|        27.0 | 10_20        |
|        25.0 | 10_20        |
|        53.2 | 40_50        |

``` r
exostosis_df |>
  mutate(fhp_category = as.numeric(fhp_category)) |>
  filter(fhp_category > 7) |> 
  select(fhp_category)
```

    ## # A tibble: 1 × 1
    ##   fhp_category
    ##          <dbl>
    ## 1         30.8

The dataset shows several issues where categorical variables do not
fully match their underlying continuous measures. For instance,
`age_group` has two missing entries, one participants aged 0–17, a range
that was not included in the defined classification range, while another
who aged 45 is miss-classified into group 1.

A few classification errors among `eop_size_mm` and `fhp_size_mm` were
corrected, mainly caused by inconsistencies in whether boundaries were
treated as inclusive or exclusive.

Besides, `eop_shape` includes categories 1, 2, 3, and 5, but category 4
is missing, while over 500 observations are recorded as NA, suggesting
incomplete or inconsistent coding.

In `fhp_category`, one record has a value of 30.8, which by definition
should fall within the 30–40 range but was not properly categorized.
Additionally, six missing values were identified in `fhp_size_mm`,
meaning that a few participants lack corresponding FHP measurements.

# Visualization

``` r
Figure_3_advanced = 
  exostosis_clean |>
  filter(!is.na(age_group), !is.na(fhp_size_mm)) |>
  ggplot(aes(x = age_group, y = fhp_size_mm, fill = sex)) +
  geom_violin(width = 0.7, alpha = 0.5) +
  geom_boxplot(width = 0.2, position = position_dodge(width = 0.7)) +
  labs(
    title = "Distribution of FHP by Age Group and Sex",
    x = "Age Group (years)",
    y = "FHP Size (mm)",
    fill = "Sex"
  ) +
  theme(legend.position = "right",
        axis.title.y = element_text(size = 8),
    plot.caption = element_text(size = 5, hjust = 0.5)
  )
```

``` r
Figure_4_advanced =
  exostosis_clean |>
  mutate(
    enlarged = 
      if_else(eop_size %in% c("10_15", "15_20", "20_25", "25+"), 1, 0)
  ) |>
  filter(!is.na(age_group), !is.na(sex)) |>    
  group_by(age_group, sex) |>
  summarise(
    total = n(),
    enlarged_n = sum(enlarged, na.rm = TRUE),
    rate = enlarged_n / total * 100
  ) |>
  ggplot(aes(x = age_group, y = rate, color = sex, group = sex)) +
  geom_line(linewidth = 1) +
  geom_point(size = 3) +
  scale_y_continuous(labels = scales::percent_format(scale = 1)) +
  labs(
    title = "Rate of Enlarged EOP by Age Group and Sex",
    x = "Age Group (years)",
    y = "Rate of Enlarged EOP",
    color = "Sex"
  ) +
  theme(legend.position = "right",
        axis.title.y = element_text(size = 8),
    plot.caption = element_text(size = 5, hjust = 0.5)
)
```

    ## `summarise()` has grouped output by 'age_group'. You can override using the
    ## `.groups` argument.

``` r
combined_plot = 
  (Figure_3_advanced / Figure_4_advanced) +
   plot_annotation(
    caption = "Combined visualization of FHP and EOP patterns across age and sex groups."
  )
combined_plot
```

<img src="P8105_mtp_bz2561_files/figure-gfm/unnamed-chunk-8-1.png" width="90%" />

Across age groups, males exhibit both greater forward head protraction
and a higher prevalence of enlarged EOP, suggesting a stronger
morphological adaptation potentially linked to prolonged mechanical
loading. The mid-age decline and later increase in both metrics may
indicate age-related variation in postural stress or bone remodeling
responses.

``` r
exostosis_clean |>
  filter(!is.na(age_group)) |>
  ggplot(aes(x = fhp_size_mm, y = eop_size_mm, color = sex)) +
  geom_point(alpha = 0.7, size = 1.5) +
  facet_grid(sex ~ age_group) +
  scale_color_manual(values = c("female" = "navy", "male" = "green")) +
  labs(
    title = "Association between FHP Size and EOP Size across Age and Sex",
    x = "Forward Head Protraction Size (mm)",
    y = "EOP Size (mm)",
    color = "Sex"
  ) +
  theme_bw(base_size = 11) +
  theme(
    strip.text = element_text(size = 10, face = "bold"),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )
```

<img src="P8105_mtp_bz2561_files/figure-gfm/unnamed-chunk-9-1.png" width="90%" />

This plot shows how FHP size relates to EOP size across age and sex
groups. The relationship appears weak in both sexes, with scattered data
and no clear trend within age categories. Males exhibit greater
variability and generally larger EOP sizes, consistent with prior
findings. Overall, EOP enlargement seems more influenced by sex than by
FHP size.

# Reproducing reported results and discussion
